# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c4d93f81-4be3-48a4-863a-59d65c921d3a";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c4d93f81-4be3-48a4-863a-59d65c921d3a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/mnt/storage/" =
    { device = "/dev/disk/by-uuid/057c6016-ea9d-47b4-b978-f6d601eb258f";
      fsType = "btrfs";
      options = [ "subvol=storage" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/26F4-68E5";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
